webtalk_init -webtalk_dir /home/moikawa/proj_Mitsuhashi/NexysVideo_UdpTest/UDP.sim/sim_1/behav/xsim/xsim.dir/tb_TOP_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 28 12:23:25 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211387882_1777527812_210663870_360" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c0a76959-49e2-43e6-ae15-6251fefe079a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f619144b7f30438e8745dc5ae5f7edce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "236" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.199 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "13 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "132784_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2949720191 -regid "211387882_1777527812_210663870_360" -xml /home/moikawa/proj_Mitsuhashi/NexysVideo_UdpTest/UDP.sim/sim_1/behav/xsim/xsim.dir/tb_TOP_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/moikawa/proj_Mitsuhashi/NexysVideo_UdpTest/UDP.sim/sim_1/behav/xsim/xsim.dir/tb_TOP_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/moikawa/proj_Mitsuhashi/NexysVideo_UdpTest/UDP.sim/sim_1/behav/xsim/xsim.dir/tb_TOP_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
