# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tmitsuhashi/bin/vivado_h30/UDP/UDP.srcs/sources_1/ip/image_queue/image_queue.xci
# IP: The module: 'image_queue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tmitsuhashi/bin/vivado_h30/UDP/UDP.srcs/sources_1/ip/image_queue/image_queue.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_queue'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tmitsuhashi/bin/vivado_h30/UDP/UDP.srcs/sources_1/ip/image_queue/image_queue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_queue'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tmitsuhashi/bin/vivado_h30/UDP/UDP.srcs/sources_1/ip/image_queue/image_queue.xci
# IP: The module: 'image_queue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tmitsuhashi/bin/vivado_h30/UDP/UDP.srcs/sources_1/ip/image_queue/image_queue.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_queue'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tmitsuhashi/bin/vivado_h30/UDP/UDP.srcs/sources_1/ip/image_queue/image_queue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_queue'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
